### ISSUE TITLE
ArgumentError: illegal key name: block_terminates_paragraph

### ISSUE THREAD

**Issue by brlafreniere** [asciidoctor/asciidoctor#1584]
ArgumentError: illegal key name: block_terminates_paragraph
        at OpalClass.$new (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:2783:17)
        at OpalModule.def.$raise (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:2434:31)
        at OpalModule.$define (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:5996)
        at /home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:6233
        at /home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:6601
        at /home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:31491
        at Object.Asciidoctor (/home/blaine/projects/crisp-wiki/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:10:31548)
        at Object.exports.convert (/home/blaine/projects/crisp-wiki/asciidoc.js:11:33)
        at /home/blaine/projects/crisp-wiki/index.js:14:25
        at Layer.handle [as handle_request] (/home/blaine/projects/crisp-wiki/node_modules/express/lib/router/layer.js:95:5)

Not sure exactly what's going on here, and I can't find much information about this error, so, I thought I'd post it here.

**Comment by brlafreniere** [comment]
Realized I should have posted this in asciidoctor.js, which I have posted there.
