### ISSUE TITLE
Permission denied on stylesdir breaks html build

### ISSUE THREAD

**Issue by dustinblack** [asciidoctor/asciidoctor#1620]
When building with the html backend, if a stylesheet is not explicitly defined and there is no write access to the stylesdir -OR- if a stylesheet is explicitly defined and there is no read access to the stylesdir, the asciidoctor command will fail with a Permission denied error.

```bash
$ asciidoctor -v -a stylesheet=mystyle.css mydoc.adoc --trace
/home/user/.gem/ruby/gems/asciidoctor-1.5.3/lib/asciidoctor.rb:1554:in `initialize': Permission denied @ rb_sysopen - /style/asciidoc.css (Errno::EACCES)
	from /home/user/.gem/ruby/gems/asciidoctor-1.5.3/lib/asciidoctor.rb:1554:in `open'
	from /home/user/.gem/ruby/gems/asciidoctor-1.5.3/lib/asciidoctor.rb:1554:in `convert'
	from /home/user/.gem/ruby/gems/asciidoctor-1.5.3/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
	from /home/user/.gem/ruby/gems/asciidoctor-1.5.3/lib/asciidoctor/cli/invoker.rb:86:in `each'
	from /home/user/.gem/ruby/gems/asciidoctor-1.5.3/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
	from /home/user/.gem/ruby/gems/asciidoctor-1.5.3/bin/asciidoctor:14:in `<top (required)>'
	from /home/user/bin/asciidoctor:23:in `load'
	from /home/user/bin/asciidoctor:23:in `<main>'
```

In this scenario, the :stylesdir: is defined in the header section of mydoc.adoc as /style and the /style directory is mode 700.

```bash
$ grep style mydoc.adoc 
:stylesdir: /style

$ ls -ld /style/
drwx------. 2 root root 4096 Dec 18 15:11 /style/
````
The problem here is that I am maintaining the stylesheet separately in a git repository. A jenkins job maintains the stylesheet on a web server. When the html is created from the asciidoc source, it must include an absolute path to the location of the mystyle.css file located on the web server. The :stylesdir: attribute in the asciidoc with the '-a stylesheet=mystyle.css' command flag will accomplish this required html output. However, when the jenkins server calls 'asciidoctor -v -a stylesheet=mystyle.css mydoc.adoc' via its 'Execute shell' build function, the asciidoctor command will fail due to no read permissions on /style. Read permissions should not be required to output the necessary html.

**Comment by mojavelinux** [comment]
> I am maintaining the stylesheet separately in a git repository...the asciidoc source must include an absolute path to the location of the mystyle.css file located on the web server.

Then what you are looking for is the following:

```
asciidoctor -a stylesheet=mystyle.css -a linkcss -a copycss! mydoc.adoc 
```

By default, Asciidoctor embeds the referenced stylesheet into the generated document. Therefore, it fail in this scenario if the file can't be read because otherwise it can't created the generated document as requested.

It appears what you want to do is link to the stylesheet, not embed it. In that case, you'll want to enable the `linkcss` attribute and disable the `copycss` attribute, as shown above.

Btw, I recommend defining the `stylesdir` attribute when calling the `asciidoctor` rather than in the document header since it is environment-specific information.

```
asciidoctor -a stylesheet=mystyle.css -a linkcss -a copycss! -a stylesdir=/styles mydoc.adoc 
```

You could also just use:

```
asciidoctor -a stylesheet=/styles/mystyle.css -a linkcss -a copycss! mydoc.adoc 
```

**Comment by mojavelinux** [comment]
For more info, see:

* http://asciidoctor.org/docs/user-manual/#styling-the-html-with-css
* http://asciidoctor.org/docs/user-manual/#applying-a-theme
