### ISSUE TITLE
Callout IDs not unique when using tables with docbook backend

### ISSUE THREAD

**Issue by hohlerde** [asciidoctor/asciidoctor#1626]
The code below produces a fop exception:
```
SEVERE: Exception
org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: Property ID "CO1-1" (found on "fo:inline") previously used; ID values must be unique within a document! (See fo:inline, id=CO1-1)
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: Property ID "CO1-1" (found on "fo:inline") previously used; ID values must be unique within a document! (See fo:inline, id=CO1-1)
	at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:304)
	at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:130)
	at org.apache.fop.cli.Main.startFOP(Main.java:177)
	at org.apache.fop.cli.Main.main(Main.java:208)
```

Compiled with:
```
asciidoctor -b docbook test.adoc
fopub test.xml
```

Version used:
```
Asciidoctor 1.5.2 [http://asciidoctor.org]
Runtime Environment (ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

test.adoc
```
= Title

== Heading 1
[cols="2"]
|====
|Col1
a|
[source, json]
----
{
"test": 1 <1>
}
----
<1> First Callout
|====

== Heading 2

[cols="2"]
|====
|Col1
a|
[source, json]
----
{
"test": 2 <1>
}
----
<1> Second Callout
|====
```

**Comment by mojavelinux** [comment]
Yep, this is a problem (and also a missing test). The callout offset (i.e., start number) needs to be inherited from the parent document (since AsciiDoc table cells are embedded documents).
