### ISSUE TITLE
nullptr upon first use

### ISSUE THREAD

**Issue by axd1967** [asciidoctor/asciidoctor#1707]
after migrating from PyCharm 4.5x to PyCharm5, at first opening of an .adoc file (which opened fine in 4.5x), I got this:

I also remember there was an error dialog box that appeared when PyCharm was started, something about a plugin, possibly related to this issue.

```
null
java.lang.NullPointerException
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor.<init>(AsciiDocPreviewEditor.java:183)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditorProvider.createEditor(AsciiDocPreviewEditorProvider.java:59)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.dumbModeFinished(FileEditorManagerImpl.java:193)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$300(FileEditorManagerImpl.java:103)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$3$1.run(FileEditorManagerImpl.java:171)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

workarounds seems to be to close PyCharm and open again...

**Comment by Mogztter** [comment]
I think this issue is related to the Intellij IDEA plugin. If this is the case, you should open an issue here: https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues

**Comment by mojavelinux** [comment]
Agree. @axd1967 let me know when you've opened the issue in the other repository and I'll close this one.
