### ISSUE TITLE
AsciidoctorJ build fails on JRuby 9.1.0.0 on Win 10

### ISSUE THREAD

**Issue by robertpanzer** [asciidoctor/asciidoctor#1752]
I just tried to build the current AsciidoctorJ 1.6.0 branch with JRuby 9.1.0.0.
Unfortunately the tests fail with this error: 

```
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: C:/Users/.../asciidoctorj/asciidoctorj-core/build/resources/test/documentwithnotexistingfile.adoc: Failed to load AsciiDoc document - can't modify frozen String
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1437)
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1409)
	at org.jruby.RubyKernel.warn(org/jruby/RubyKernel.java:1167)
	at RUBY.preprocess_include(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:868)
	at RUBY.process_line(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:632)
	at RUBY.peek_line(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:162)
	at RUBY.peek_line(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:665)
	at RUBY.skip_blank_lines(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/reader.rb:319)
	at RUBY.next_section(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:278)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/parser.rb:67)
	at RUBY.parse(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor/document.rb:471)
	at RUBY.load(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1344)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1462)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.4/lib/asciidoctor.rb:1576)
	at RUBY.convertFile(<script>:68
```

Seems like JRuby 9.1.0.0 doesn't like variables inside %w on Windows, because this line looks like this:
```ruby
          warn %(asciidoctor: WARNING: #{line_info}: include file not found: #{include_file})
```

I'll also file an issue for JRuby.

**Comment by mojavelinux** [comment]
I'm not sure what change we should make to Asciidoctor core given that this appears to be a JRuby regression. The test in question succeeds on Linux.

**Comment by mojavelinux** [comment]
I did notice that there is failed test later in the suite when using JRuby 9.1.0.0 on Linux.

org.asciidoctor.integrationguide.extension.YellBlockProcessorTest#should_invoke_block_processor

```
java.lang.NullPointerException
	at org.jruby.java.proxies.MapJavaProxy$RubyHashMap.visitAll(MapJavaProxy.java:261)
	at org.jruby.RubyHash.replaceCommon(RubyHash.java:1870)
	at org.jruby.RubyHash.replace(RubyHash.java:1845)
```

**Comment by robertpanzer** [comment]
I found this one as well yesterday and will fix it.
This is my error:)

Am Montag, 9. Mai 2016 schrieb Dan Allen :

**Comment by mojavelinux** [comment]
Thanks @robertpanzer!

**Comment by robertpanzer** [comment]
Should be fixed with https://github.com/asciidoctor/asciidoctorj/pull/461

**Comment by mojavelinux** [comment]
:+1:
