### ISSUE TITLE
Is AsciiDoctor published to npm registry?

### ISSUE THREAD

**Issue by richnsoos** [asciidoctor/asciidoctor#1914]
Is asciidoctor published at https://registry.npmjs.org/asciidoctor? Currently, it shows `{}`.

This is the error that I get:
```
~/workspaces/7ps-docs (latest)$ npm install asciidoctor
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "asciidoctor"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/asciidoctor
npm ERR! 404
npm ERR! 404  'asciidoctor' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sth787/workspaces/7ps-docs/npm-debug.log
```

*/Users/sth787/workspaces/7ps-docs/npm-debug.log*

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'asciidoctor' ]
2 info using npm@3.10.9
3 info using node@v4.4.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData asciidoctor
8 silly fetchNamedPackageData asciidoctor
9 silly mapToRegistry name asciidoctor
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'asciidoctor',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'asciidoctor',
12 silly mapToRegistry   name: 'asciidoctor',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/asciidoctor
14 verbose request uri https://registry.npmjs.org/asciidoctor
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:17:46 PM
17 verbose request id b4f6174cf2625dc4
18 http request GET https://registry.npmjs.org/asciidoctor
19 http 404 https://registry.npmjs.org/asciidoctor
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Mon, 07 Nov 2016 20:17:47 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'close',
20 verbose headers   'x-served-by': 'cache-iad2641-IAD',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1478549867.125682,VS0,VE28',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Mon, 07 Nov 2016 20:17:47 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'close',
21 silly get     'x-served-by': 'cache-iad2641-IAD',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1478549867.125682,VS0,VE28',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/asciidoctor
22 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:77:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
22 silly fetchPackageMetaData  error for asciidoctor { [Error: Registry returned 404 for GET on https://registry.npmjs.org/asciidoctor] pkgid: 'asciidoctor', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/asciidoctor
27 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
27 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
27 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
27 verbose stack     at emitTwo (events.js:87:13)
27 verbose stack     at Request.emit (events.js:172:7)
27 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
27 verbose stack     at emitOne (events.js:77:13)
27 verbose stack     at Request.emit (events.js:169:7)
27 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
28 verbose statusCode 404
29 verbose pkgid asciidoctor
30 verbose cwd /Users/sth787/workspaces/7ps-docs
31 error Darwin 15.6.0
32 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "asciidoctor"
33 error node v4.4.5
34 error npm  v3.10.9
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/asciidoctor
37 error 404
38 error 404 'asciidoctor' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
```

**Comment by Mogztter** [comment]
Hello Susan,

The package name is asciidoctor.js, not asciidoctor.

**Comment by richnsoos** [comment]
Thank you
