### ISSUE TITLE
Unreadable characters in output file name

### ISSUE THREAD

**Issue by perpetuum-mobile** [asciidoctor/asciidoctor#2085]
I'm using asciidoctor (via CLI) version 1.5.5 and ruby 2.0.0 on windows server 2003.
I need to specify output file name using non-latin (in my case Cirillic/Russian) latters. For example:
when I type
`asciidoctor -o "тестовый документ.html" index.adoc`
the result file has name
`ЄхёЄют√щ фюъєьхэЄ.html`
The same command on linux works fine.
Is there a way to fix it without changing your code?

**Comment by mojavelinux** [comment]
This seems me like an encoding issue in the console. Can you verify that the console is running in UTF-8 mode?

    chcp 65001

I explain what this does in the README. See https://github.com/asciidoctor/asciidoctor#requirements

If that doesn't do it, then we'll need to dig further to see what's going on.

**Comment by perpetuum-mobile** [comment]
I've changed codepage in the console to UTF-8. 
On win server 2003 the command ran with no output to console and no html file was generated even when in output file name were only latin letters:
`asciidoctor -o "doc.html" index.adoc`
When codepage in the console is 866 (native to this OS), running 
`asciidoctor -o "doc.html" index.adoc`
produces valid file with name doc.html.
When I run the same command on win 10 console with codepages 866 or 65001, the valid file is generated. But when I run on win 10 console with codepage 65001 command with russian letters:
`asciidoctor -o "документ.html" index.adoc`
the output is:
`C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:346:in 'match': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:346:in 'parse_arg'
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:499:in 'parse'
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:1392:in 'block in parse_in_order'
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:1351:in 'catch'
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:1351:in 'parse_in_order'
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:1345:in 'order!'
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:1437:in 'permute!'
        from C:/ntools/Ruby200-x64/lib/ruby/2.0.0/optparse.rb:1459:in 'parse!'
        from C:/ntools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/options.rb:143:in 'parse!'
        from C:/ntools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/options.rb:33:in 'parse!'
        from C:/ntools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:22:in 'initialize'
        from C:/ntools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/asciidoctor-1.5.5/bin/asciidoctor:12:in 'new'
        from C:/ntools/Ruby200-x64/lib/ruby/gems/2.0.0/gems/asciidoctor-1.5.5/bin/asciidoctor:12:in '<top (required)>'
        from C:/ntools/Ruby200-x64/bin/asciidoctor:23:in 'load'
        from C:/ntools/Ruby200-x64/bin/asciidoctor:23:in '<main>'`

**Comment by mojavelinux** [comment]
I believe this is similar to #1969. If the internal encoding is not UTF-8, the filenames are not UTF-8 encoded.

However, in this case, the error seems to be coming from optparse. We can't fix code in Ruby itself.
