### ISSUE TITLE
Getting error Match to convert at .epub and .pdf

### ISSUE THREAD

**Issue by nelruk** [asciidoctor/asciidoctor#2292]
I've been working on my project. When I print in `html` everything is fine but when I do a .epub, .pdf conversion I get this error:

`ERROR => Problem occured while selecting Match
org.xml.sax.SAXParseException: The element type "span" must be terminated by the matching end-tag "</span>".`

```
at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)

	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)

	at org.joox.JOOX.$(JOOX.java:268)

	at com.kodcu.other.IOHelper.$(IOHelper.java:176)

	at com.kodcu.service.convert.docbook.DocBookConverter.lambda$convert$1(DocBookConverter.java:65)

	at com.kodcu.service.ThreadService$1.call(ThreadService.java:53)

	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)

	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)

	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)

	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

I don't know how to fix it..

**Comment by mojavelinux** [comment]
There's not enough information here to act on. I need to have at least a
sample AsciiDoc file that exhibits this error. Otherwise, I have no idea
what I'm looking for. Thanks!

**Comment by mojavelinux** [comment]
Please reopen when you have a sample document to share.

It appears you are attempting to parse the DocBook output using an XML parser and there is a mismatched `<span>` element somewhere in the source.
