### ISSUE TITLE
Random processing errors on build server (using pygments.rb)

### ISSUE THREAD

**Issue by miltador** [asciidoctor/asciidoctor#2341]
From time to time `asciidoctor` fails with this error on our build server (output with `--trace` argument):
```
[16:39:09]	[Step 7/8] ERROR 2017/07/27 15:42:08 /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/substitutors.rb:139:in `apply_subs': undefined method `split' for nil:NilClass (NoMethodError)
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/block.rb:118:in `content'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/converter/html5.rb:618:in `listing'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/converter/base.rb:34:in `convert'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:70:in `convert'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:79:in `block in content'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:79:in `map'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:79:in `content'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/converter/html5.rb:358:in `section'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/converter/base.rb:34:in `convert'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:70:in `convert'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:79:in `block in content'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:79:in `map'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/abstract_block.rb:79:in `content'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/document.rb:1120:in `content'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/converter/html5.rb:283:in `embedded'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/converter/base.rb:34:in `convert'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/document.rb:1060:in `convert'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor.rb:1502:in `convert'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/lib/asciidoctor/cli/invoker.rb:99:in `invoke!'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/BuildAgent/work/823684b5d69f9894/vendor/asciidoctor/bin/asciidoctor:14:in `<top (required)>'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/.rvm/gems/ruby-2.3.1/bin/asciidoctor:23:in `load'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/.rvm/gems/ruby-2.3.1/bin/asciidoctor:23:in `<main>'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
[16:39:11]	[Step 7/8] ERROR 2017/07/27 15:42:08 from /home/teamcity/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

It is very random error, if I just restart the build it is gone.

However, if it fails, it fails on a specific `.adoc` file, I can send you it by email if needed.

Asciidoctor version: `1.5.6.1`
Ruby version:
```
Runtime Environment (ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

**Comment by mojavelinux** [comment]
That is, indeed, very surprising. I can't even guess what might be going wrong. Could you send me the input file?

**Comment by miltador** [comment]
I sent the file to you by email.

**Comment by mojavelinux** [comment]
I received the files, but I have no idea how to make them fail. For me, it works. But I highly suspect it's all in how Asciidoctor is executed. Can you tell me how you are using Asciidoctor?

**Comment by mojavelinux** [comment]
You know what I'm thinking. There's a chance that Pygments is somehow not returning successfully and that leaves Asciidoctor will a nil value during substitution. I wonder if that's what's happening. I'm going to test that theory.

**Comment by mojavelinux** [comment]
That's exactly what it is. So pygments.rb seems to be unreliable, perhaps under heavy load or in certain CI environments.

I can put in a fallback to use the original text if the Pygments highlight fails to return a string.

In general, pygments.rb makes me extremely nervous because it uses a background process to communicate with Python. This is why I advocate for the use of [Rouge](https://github.com/jneen/rouge), which is a pure Ruby library that does basically the same thing as Pygments.

**Comment by mojavelinux** [comment]
Specifically, the request to highlight timed out. This is what happens when the timeout limit is reached. But again, the check is the same.

**Comment by miltador** [comment]
Wow, a big thanks for diving into this! I will probably consider switching to Rouge then! Couldn't thought that it could be pygments issue.

**Comment by miltador** [comment]
I am using Hugo as a static website generator. It has support for `asciidoctor` as a source of content.

**Comment by miltador** [comment]
@mojavelinux, just for clarification, about using Rouge:
[here](http://asciidoctor.org/docs/user-manual/#available-source-highlighters) in the table of supported highlighters it is said that Rouge is supported only for Asciidoctor PDF environment. Can I use it for Asciidoctor with HTML backend?

**Comment by miltador** [comment]
Also it would be great to know how to configure it's theme or css rules, with pygments I can do this:
```
:pygments-style: monokai
:pygments-css: inline
```
What about Rouge?

**Comment by mojavelinux** [comment]
Rouge isn't formally integrated into Asciidoctor core yet. That's #1040. And this is exactly why we're doing it. You could wait or try to integrate it as an extension before that.

**Comment by mojavelinux** [comment]
For rouge, it would be the same:

```
:rouge-style: monokai
:rouge-css: inline
```

**Comment by mojavelinux** [comment]
PR sent at #2342.
