### ISSUE TITLE
Creating document programatically

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor#2378]
I have set myself a simple task of programatically generating a changelog from commits on Gitlab using Asciidoctor.

What I wish to do is:

* Open an existing document, e.g. `CHANGELOG.adoc`
* Find a particular level of heading (e.g. the second level heading which matches the word 'version')
* Create some new headings and under each create an unordered list related to the number of commits.

I'm particularly struggling with extracting some Asciidoc source after creating a section and a list of items. Below is a small litany of things which haven't worked especially well.

```ruby
#!/usr/bin/ruby

require 'asciidoctor'

document = Asciidoctor::Document.new

section = Asciidoctor::Section.new
section.title = 'Section 1'
section.id = 'sect1'

document << section
document << Asciidoctor::Block.new(document, :paragraph, :source => '_This_ is a <test>')

list1 = Asciidoctor::List.new(document, :paragraph)
document << list1

list1 << Asciidoctor::ListItem.new(list1, text="doda doda")
list1 <<  Asciidoctor::ListItem.new(list1, text="eyore eyore")

puts document.source()
puts document.content
puts document.blocks()
puts document.parse()

options = { to_file => false, header_footer => true}
puts document.render_file()
puts document.parse
```
I get a range of errors depending on my somewhat random experimentation, for instance:

```
/usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:70:in `convert': undefined method `playback_attributes' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `block in content'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `map'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:80:in `content'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1108:in `content'
        from ./test.rb:21:in `<main>'
```

I also played with `puts document.render(:doctype => 'inline')` and received 

```
/usr/lib/ruby/vendor_ruby/asciidoctor/substitutors.rb:168:in `extract_passthroughs': undefined method `compat_mode' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/asciidoctor/substitutors.rb:104:in `apply_subs'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/substitutors.rb:150:in `apply_title_subs'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/abstract_block.rb:128:in `title'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:641:in `doctitle'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:728:in `save_attributes'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:713:in `finalize_header'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:147:in `parse_document_header'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/parser.rb:63:in `parse'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:475:in `parse'
        from /usr/lib/ruby/vendor_ruby/asciidoctor/document.rb:1027:in `convert'
        from ./test.rb:26:in `<main>'
```

Am I trying to do a "wrong thing"? Other than directly converting a file, there doesn't seem to be a lot of others using native methods like this so my google fu was poor. It would be nice to have a little more documentation under http://asciidoctor.org/#ruby-api or http://asciidoctor.org/docs/user-manual/#api

I can certainly more easily create a few functions which look for section headers and create lists with a little regex and string manipulation but I thought it would be better to use Asciidoctor native methods.

**Comment by cristoper** [comment]
I am playing with the Asciidoctor API for the first time, so I am far from an expert. But I think your main problem is the hierarchy of your blocks (the parent of the list should be the section rather than the document, for example). It is awkward that Asciidoctor makes you specify the parent and then also makes you append it to the parent, that seems redundant. There is [a comment in abstract_block.rb](https://github.com/asciidoctor/asciidoctor/blob/59617dab4401350efcd4e50403555fa34926ed46/lib/asciidoctor/abstract_block.rb#L242-L243) which reads "parent assignment pending refactor" so I guess the plan is to set the parent automatically in the future.

You also have a secondary problem caused by setting your list's context as `:paragraph` when I think it should be either `:ulist` or `:olist`.

This works for me:

````ruby
require 'asciidoctor'

document = Asciidoctor::Document.new

# section is our root block
section = Asciidoctor::Section.new(parent=document)
section.title = 'Section 1'
document << section

# paragraph is a child of section
paragraph = Asciidoctor::Block.new(section, :paragraph, :source => '_This_ is a <test>')
section << paragraph

# list1 is also a child of section
list1 = Asciidoctor::List.new(section, :ulist)
# the ListItem is a child of list1
list1 << Asciidoctor::ListItem.new(list1, text="doda doda")
section << list1

document.render
````

Produces:

````html
<div class=\"sect1\">\n<h2>1. Section 1</h2>\n<div class=\"sectionbody\">\n<div class=\"paragraph\">\n<p>_This_ is a <test></p>\n</div>\n<div class=\"ulist\">\n<ul>\n<li>\n<p>doda doda</p>\n</li>\n</ul>\n</div>\n</div>\n</div>
````

**Comment by mojavelinux** [comment]
> It is awkward that Asciidoctor makes you specify the parent and then also makes you append it to the parent, that seems redundant. 

This was an issue I've been meaning to file. See https://github.com/asciidoctor/asciidoctor/issues/2398

**Comment by mojavelinux** [comment]
It's important to understand that Asciidoctor is gradually evolving to support this usage. When Asciidoctor was started, the API was developed with only built-in converters in mind. When the extensions API was added, it started to open up that API for external usage. But there were gaps between when an external consumer needed and what was needed internally. Those gaps need to be closed.

In a future major release of Asciidoctor, we may even reevaluate this schema-less node API and go with something that is more formally typed. Again, that was not an original design goal, so I picked up what Asciidoctor already had an did the simplest thing that would work.

Let's identify each thing we need improved and turn that into an issue that we can act on.

**Comment by mojavelinux** [comment]
> document = Asciidoctor::Document.new

You should use Asciidoctor.load to create a blank document or else certain things won't be properly initialized.

```
doc = Asciidoctor.load []
```

**Comment by mojavelinux** [comment]
This is rather crude, but should give you what you want:

```ruby
require 'asciidoctor'

changes_by_version = {
  '1.0' => ['a', 'b', 'c'],
  '2.0' => ['foo', 'bar', 'baz']
}

doc = Asciidoctor.load_file 'CHANGELOG.adoc', safe: :safe, header_footer: true

doc.find_by(context: :section) {|candidate| candidate.title.include? 'Version' }.each do |vsect|
  vsect_title = vsect.title
  version = vsect_title.slice(vsect_title.index('Version') + 8, vsect_title.length)
  category = Asciidoctor::Section.new vsect, (vsect.level + 1)
  category.title = 'Category X'

  ulist = Asciidoctor::List.new category, :ulist
  changes_by_version[version].each do |change|
    list_item = Asciidoctor::ListItem.new ulist, change
    ulist << list_item
  end
  category << ulist
  vsect << category
end

puts doc.convert
```

**Comment by danyill** [comment]
Thank you @cristoper and @mojavelinux for your help - that is what I had in mind. I was hoping to extract asciidoctor source for the changes a script like this would produce as the raw content will need some modification before it is correct (messy commit messages etc.)?

I tried:

* `puts doc.source` would seem to be the [obvious candidate](http://www.rubydoc.info/gems/asciidoctor/Asciidoctor/Document#source-instance_method), but it only provides the original document.
* Perhaps `puts doc.parse.source` but nup.
* Looking at the [coalescer script](https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb) I thought perhaps `doc.reader.read`.

Each of these only produces the source document without modifications, even though `doc.convert` produces html5 with the correct changes.

Is this something which must wait for #1793? 

Incidentally, I am happy to be ignored if I am abusing the issue management system as a personal support desk... :cry:

**Comment by mojavelinux** [comment]
At the moment, the Asciidoctor processor isn't really a source to source processor. I've done that on various projects, but it's always a bit hacky as that's not been a design goal of the processor. Again, it's evolving, so it may evolve into that.

I can share the technique I use. It does require some tricks and creative solutions.

**Comment by mojavelinux** [comment]
Basically, what I do is parse the document with the sourcemap option enabled and parse option disabled. Then I grab the source lines, then parse the document. I then use the information from the AST to manipulate the raw lines, then write the raw lines out to disk.

It looks something like this:

```ruby
def load_document source
  old_verbose, $VERBOSE = $VERBOSE, nil
  @doc = ::Asciidoctor.load source,
      safe: :safe,
      parse: false,
      sourcemap: true,
      attributes: {
        'docfile' => @source_path,
        'idprefix' => '',
        'idseparator' => '-'
      }
  @source_lines = @doc.source_lines
  @doc.parse
  nil
ensure
  $VERBOSE = old_verbose
end

def transform_tabsets
  (@doc.find_by context: :tabset).each do |tabset|
    first_line = tabset.lineno - 1 
    last_line = first_line + tabset.lines.size + 2 
    boundaries = [@source_lines[first_line], @source_lines[last_line - 1]]
    unless boundaries[0] == boundaries[1] && boundaries[0] == '-' * boundaries[0].length
      warn %(parser not aligned with boundaries of tab set at #{@source_path}:#{tabset.lineno})
      next
    end
    @source_lines[first_line - 1] = '[.ex]'
    @source_lines[first_line] = @source_lines[last_line - 1 ] = '====='
  end
  nil
end
```

**Comment by mojavelinux** [comment]
> Is this something which must wait for #1793?

I'd say not really because generating / manipulating a source document is very different from generating output documents. There is information you need to rebuild a source document that the processor throws away. I think to do this right, it's actually a separate processor. It's more like the validation processor that I'm starting to build. That processor keeps information about the source and is able to reproduce it. These are just very different needs and I don't think single processor can serve all those needs (and not become bloated, slow or monolithic).

**Comment by mojavelinux** [comment]
> Each of these only produces the source document without modifications, even though doc.convert produces html5 with the correct changes.

What I had originally suggested was on-the-fly AST transformations. Those will only be seen in the output since it only changes the AST in memory. Again, that's a distinct use case from modifying the source.

**Comment by mojavelinux** [comment]
In other words, the title of this issue is actually two different things.

> Creating document programatically

There's (a) creating the document programmatically in order to produce and output document, and there's (b) creating the document programmatically in order to produce an input document.

**Comment by danyill** [comment]
Thanks again @mojavelinux. I might have thought that doing (b) facilitated (a) in some superset like fashion?

**Comment by mojavelinux** [comment]
Nope. The best way to describe is that the processor was built with a single goal in mind, to make an output document. Creating an input document requires additional information that we simply don't capture or track because we haven't needed it. That's where we have to come back in and rethink. I'm convinced that these concerns are so different that it should be a separate processor. I don't want the main processor to have to do a bunch of work it doesn't need to do just to handle the case of source to source or validation. Separating the concerns is a better strategy.

**Comment by mojavelinux** [comment]
FYI, the asciidoc-coalescer.rb script has been redesigned and published as the [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer). It has also been released to RubyGems.org as a gem named **asciidoctor-reducer**. You can find installation instructions in the README for that project.
