### ISSUE TITLE
Publishing to confluence fails when included file has regex content

### ISSUE THREAD

**Issue by samuelstein** [asciidoctor/asciidoctor#2444]
hello, 
i have a problem with a file include. I want to include a json file which contains a regex:
```
"instanceVersionDate": {  
  "type": "string",  
  "pattern": "[0-9][0-9]\.[0-9][0-9]\.[0-9]{4}$",  
  "optional": false
}
```

now the publishing to confluence fails with the following exception:
`Caused by: org.apache.maven.plugin.MojoExecutionException: Publishing to Confluence failed
        at org.sahli.asciidoc.confluence.publisher.maven.plugin.AsciidocConfluencePublisherMojo.execute(AsciidocConfluencePublisherMojo.java:75)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.RuntimeException: Could not convert asciidoc pages
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluenceConverter.convert(AsciidocConfluenceConverter.java:85)
        at org.sahli.asciidoc.confluence.publisher.maven.plugin.AsciidocConfluencePublisherMojo.execute(AsciidocConfluencePublisherMojo.java:67)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluencePage.replaceAll(AsciidocConfluencePage.java:146)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluencePage.lambda$unescapeCdataHtmlContent$1(AsciidocConfluencePage.java:127)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluencePage.lambda$postProcessContent$4(AsciidocConfluencePage.java:156)
        at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:484)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluencePage.postProcessContent(AsciidocConfluencePage.java:156)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluencePage.convertedContent(AsciidocConfluencePage.java:117)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluencePage.newAsciidocConfluencePage(AsciidocConfluencePage.java:101)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluenceConverter.lambda$buildPageTree$0(AsciidocConfluenceConverter.java:97)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluenceConverter.buildPageTree(AsciidocConfluenceConverter.java:92)
        at org.sahli.asciidoc.confluence.publisher.converter.AsciidocConfluenceConverter.convert(AsciidocConfluenceConverter.java:76)
        ... 23 more`

**Comment by Mogztter** [comment]
Hello @samuelstein, I think this issue belong to https://github.com/alainsahli/confluence-publisher 😉

**Comment by samuelstein** [comment]
ok. should i open it there?

**Comment by mojavelinux** [comment]
Yes, please.
