### ISSUE TITLE
[1.5.7] Cannot use renderers (e.g. asciidoctor-diagram, asciidoctor-pdf)

### ISSUE THREAD

**Issue by cyChop** [asciidoctor/asciidoctor#2714]
> TL;DR I cannot use asciidoctor-* renderers with Asciidoctor 1.5.7.

Hi,

I'm using AsciiDoctor 1.5.7.dev because I was interested in some new features (namely what you did for #1394).

However, when I use asciidoctor-pdf or asciidoctor-diagram, I get an error:

```
asciidoctor: FAILED: C:/path/to/my/doc.asciidoc: Failed to load AsciiDoc document - superclass mismatch for class FTP
  Use --trace for backtrace
```
Using the `--trace` option, I get the following:

```
C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/uri/ftp.rb:23:in `<module:URI>': superclass mismatch for class FT
P (TypeError)

        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/uri/ftp.rb:13:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/uri.rb:107:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/css_parser-1.6.0/lib/css_parser.rb:2:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/prawn-svg-0.27.1/lib/prawn-svg.rb:6:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/prawn-svg_ext.rb:1:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:9:in `require_relative'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:9:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf.rb:3:in `require_relative'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf.rb:3:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from C:/Program Files/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.16/bin/asciidoctor-pdf:4:in `<top (required)>'
        from C:/Program Files/Ruby24-x64/bin/asciidoctor-pdf:23:in `load'
        from C:/Program Files/Ruby24-x64/bin/asciidoctor-pdf:23:in `<main>'
```

In case it can be an environment-related issue, I'm working in Windows 10 and all the gems I installed are related with my use of AsciiDoctor (I don't know Ruby).

```
> gem query --local

*** LOCAL GEMS ***

addressable (2.5.2, 2.4.0)
afm (0.2.2)
Ascii85 (1.0.3)
asciidoctor (1.5.7.dev, 1.5.6.2)
asciidoctor-diagram (1.5.10.next1, 1.5.9)
asciidoctor-pdf (1.5.0.alpha.16)
asciimath (1.0.4)
backports (3.11.3)
bigdecimal (default: 1.3.0)
builder (3.2.3)
bundler (1.16.1)
coderay (1.1.2)
css_parser (1.6.0)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
diff-lcs (1.3)
docile (1.1.5)
erubis (2.7.0)
ethon (0.11.0)
faraday (0.15.0)
faraday_middleware (0.12.2)
ffi (1.9.23 x64-mingw32)
gh (0.15.1)
gherkin (4.1.3)
haml (5.0.4)
hashery (2.1.2)
highline (1.7.10)
io-console (default: 0.4.6)
json (default: 2.0.4)
launchy (2.4.3)
multi_json (1.13.1)
multi_test (0.1.2)
multipart-post (2.0.0)
net-http-persistent (2.9.4)
net-http-pipeline (1.0.1)
openssl (default: 2.0.5)
pdf-core (0.7.0)
pdf-reader (2.1.0)
polyglot (0.3.5)
prawn (2.2.2)
prawn-icon (1.3.0)
prawn-svg (0.27.1)
prawn-table (0.2.2)
prawn-templates (0.1.1)
psych (default: 2.2.2)
public_suffix (3.0.2)
pusher-client (0.6.2)
rake (12.3.1, 12.0.0, 10.0.4)
rdoc (default: 5.0.0)
rouge (3.1.1)
rspec (3.7.0)
rspec-core (3.7.1)
rspec-expectations (3.7.0)
rspec-mocks (3.7.0)
rspec-support (3.7.1)
ruby-rc4 (0.1.5)
rubygems-update (2.7.6)
safe_yaml (1.0.4)
temple (0.8.0)
thread_safe (0.3.6)
tilt (2.0.8)
travis (1.8.8)
treetop (1.5.3)
ttfunk (1.5.1)
typhoeus (0.8.0)
websocket (1.2.5)
```

**Comment by cyChop** [comment]
Just a thank you note. AsciiDoctor is great and you're more than efficient in the solving of issues. :)
