### ISSUE TITLE
Include directive in tables broken?

### ISSUE THREAD

**Issue by ilvetz** [asciidoctor/asciidoctor#2817]
Hi all.

I've always compiled this piece of code with 1.5.6.x and it worked with every backend:

```
[format="csv", cols="1,1,3a", separator=";", options="header"]
|===
include::CHANGELOG.csv[]
|===
```

Today, after 6 month, I started to work again on my document (I lacked inspiration). I took the opportunity and I updated the toolchain.

```
Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]) (lc:CP850 fs:Windows-1252 in:CP850 ex:CP850)
```

Now that include directive break the compilation (with every backend: html5, pdf, docbook) and I had to remove the changelog. This is the trace I captured.

```
PC_187276 [0] % asciidoctor --trace -vvv src/bx-refarc.adoc                             RET:1 (feature/fondamenti L|√) ~/projects/bx-refarc
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/table.rb:345: warning: instance variable @inner_document not initialized
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/table.rb:345:in `content': undefined method `convert' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:831:in `block (3 levels) in table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:825:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:825:in `block (2 levels) in table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:823:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:823:in `block in table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:820:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:820:in `table'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38:in `convert'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:71:in `convert'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `block in content'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `map'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `content'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:354:in `section'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38:in `convert'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:71:in `convert'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `block in content'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `map'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/abstract_block.rb:80:in `content'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1209:in `content'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/html5.rb:185:in `document'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/converter/base.rb:38:in `convert'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/document.rb:1141:in `convert'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1515:in `convert'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `block in convert_file'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `open'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor.rb:1589:in `convert_file'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.7.1/bin/asciidoctor:14:in `<top (required)>'
        from C:/Ruby24-x64/bin/asciidoctor:23:in `load'
        from C:/Ruby24-x64/bin/asciidoctor:23:in `<main>'
```

It is a known issue? What can I do?

Thank you very much.

**Comment by ilvetz** [comment]
Got it.

It seems that forcing asciidoc format on the third column is not tolerated anymore.
Removing it and using `cols="1,1,3a"` resolved the issue.

Is this the right and wanted behavior @mojavelinux ?

Thank you.

**Comment by elextr** [comment]
```
= foo

|===
| a | b
a|
include::include.asciidoc[]
| b2
|===
```

works for me, could you post a minimum example that shows the problem.

**Comment by elextr** [comment]
Note that for me it also works without the cell being forced to `a` style.

**Comment by mojavelinux** [comment]
@ilvetz I'm not yet getting a complete picture of this scenario. You said:

> Removing it and using `cols="1,1,3a"` resolved the issue.

but in your original example, you have `cols="1,1,3a"`, so I'm not sure what you changed.

Do you mean that you used a cell style in the CSV somewhere? Could you paste the relevant snippet of the include file?

**Comment by mojavelinux** [comment]
What I can tell you is that when using csv as the format, you can only control styles using the cols attribute on the table. The csv format doesn't support setting styles per cell. That should have never worked.

**Comment by elextr** [comment]
Oops, missed the include was a CSV file, sorry for the noise.

**Comment by mojavelinux** [comment]
I think what you meant to say is that you removed the "a" from the colspec. When it's there, it does look like there is a bug. I'll dive into what's going on.

**Comment by mojavelinux** [comment]
Yep, this is a regression...and it's due to a missing test for this case. I'll get this fixed.

**Comment by mojavelinux** [comment]
Thanks for reporting @ilvetz!

**Comment by mojavelinux** [comment]
...and given that we document this feature, it's pretty important not to break it IMO.

https://asciidoctor.org/docs/user-manual/#formatting-cells-in-a-data-table

**Comment by ilvetz** [comment]
Sorry for the late reply, @mojavelinux. I didn't paste the right workaround which I used to solve my issue but I'm glad you were able to understand my words and solve a small bug.

**Comment by mojavelinux** [comment]
@ilvetz your point made it through and the bug is now resolved. Win win!
