### ISSUE TITLE
Encoding normalization failure?

### ISSUE THREAD

**Issue by zelivans** [asciidoctor/asciidoctor#2884]
One of the first things I immediately saw when starting to test asciidoctor is that it fails to deal with malformed binary data. I don't know if asciidoctor intends to deal with such input at all, but it throws an unhandled `Encoding::InvalidByteSequenceError` Exception when it fails to deal with the input encoding. I think it would be correct to either prevent this from happening or properly handle the exception.

I only examined the first crashes I got in which the exception is raised from `normalize_lines_array` in `helpers.rb`. I did not see any crashes in `normalize_lines_from_string` but my hunch says it also needs some care. 

Since the reference crash files are binary [I uploaded them to gist](https://gist.github.com/zelivans/74bc642add4829975e2e1f77025379e4#file-id-000001-sig-10-src-000076-op-havoc-rep-128). The two top crash lines (full in the gist):

1. 
```
/home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:78:in `encode': asciidoctor: FAILED: /home/ariel/afl-kisaten/private/sandbox/asciidoctor/encoding_crash/id:000000,sig:10,src:000048,op:havoc,rep:128: Failed to load AsciiDoc document - "\xDDc" on UTF-16BE (Encoding::InvalidByteSequenceError)
```

2. 
```
/home/ariel/afl-kisaten/private/sandbox/asciidoctor/asciidoctor/lib/asciidoctor/helpers.rb:75:in `encode': asciidoctor: FAILED: /home/ariel/afl-kisaten/private/sandbox/asciidoctor/encoding_crash/id:000001,sig:10,src:000076,op:havoc,rep:128: Failed to load AsciiDoc document - incomplete "t" on UTF-16LE (Encoding::InvalidByteSequenceError)
```

**Comment by mojavelinux** [comment]
I would argue this is the correct behavior. Asciidoctor requires the input to be UTF-8 encoded. It attempts to forcefully coerce other text encodings to UTF-8, but if that fails, the processor should fail.

**Comment by mojavelinux** [comment]
I suppose a case could be made that we want a helpful error message. But that tends to hide the source of the issue, so showing the exception is actually more useful. If we could find a way to do both, I could get behind that.

**Comment by zelivans** [comment]
Hi, thanks for the clear answer. Had a feeling this might be the case, but I wanted to start the discussion to be sure. IMO asciidoctor should own this exception and inform the user that the input was malformed (i.e. non UTF-8) and failed to convert. Then append the original Exception text. I am not sure on which level it should be done though, what do you think about using `logger.error` and then returning nil?

**Comment by mojavelinux** [comment]
Asciidoctor does report that it failed to load the document. Do you expect to see more detail in this message? Perhaps something like:

```
Failed to load AsciiDoc document because it uses an unsupported encoding - "\xDDc" on UTF-16BE
```

> what do you think about using logger.error and then returning nil?

I don't think that's the right approach. If the input document can't be read, failure is the correct outcome. It's an IO error.

This is going to be a lot easier to handle once we switch to 2.0.0 and can finally start using the native encoding capabilities of Ruby. So I think the right decision is to defer this to 2.0.0.

**Comment by mojavelinux** [comment]
> it fails to deal with malformed binary data

I don't think it's correct to say Asciidoctor fails to deal with malformed binary data. It deals with it by throwing an exception. Asciidoctor expects to receive a source document with valid encoding. A failure to deal with it would be to allow it to produce a garbage output document.

What we can improve is the message, because "invalid byte sequence in UTF-8" is not clear to someone not well versed in encodings.

Here's the exception message I propose:

```
input is either binary or contains an invalid Unicode escape sequence
```

Most of the time, the problem is that the input is binary. And since Asciidoctor doesn't convert binary documents, the appropriate response is to throw an exception.

**Comment by zelivans** [comment]
@mojavelinux looks great, agree about the files probably being binary

**Comment by mojavelinux** [comment]
\o/ Thanks for weighing in!

**Comment by bedoro** [comment]
We currently evaluate using AsciiDoctor (through `asciidoctor-maven-plugin`) for the documentation of a very large codebase. We are trying to include `.java` source files directly into the documents. All our Java-Files are encoded using CP1252 and contain special characters (i.e. ä/ö/ü). Now, I know that it would be much better to encode them in UTF-8, but there are historical and internal reasons why this is not an option.

When including the source file, we too get the error `(ArgumentError) invalid byte sequence in UTF-8`. Including source files directly into the document is one of the main reasons for using AsciiDoctor. 

Is there any way at all to work around this issue? Would it be an option to extend the `include`-directive to convert the strings to UTF-8 before converting them to binary? Are there any other options we could try or are we just SOL?

**Comment by mojavelinux** [comment]
The issue is that Java is not configured to read the files as UTF-8 (regardless of what they are encoded in). Simply add the flag `-Dfile.encoding=UTF-8` and it should do the trick. See https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding

**Comment by ysb33r** [comment]
@mojavelinux It might be useful to have an `encoding` field on the include. i.e. `include::foo.txt[encoding=cp1252]`. That can give an hint to Asciidocgtorto do a specific conversion to URF-8 from the other character set.

I'm not sure though how much additional code will have to be pulled into to do this, or whether ICU would be required as an extra.

**Comment by mojavelinux** [comment]
It's not a ton of code and I've considered it. But it's a slippery slope to
a real mess, which is my main concern.

>

**Comment by bedoro** [comment]
> The issue is that Java is not configured to read the files as UTF-8 (regardless of what they are encoded in). Simply add the flag `-Dfile.encoding=UTF-8` and it should do the trick. See https://stackoverflow.com/questions/361975/setting-the-default-java-character-encoding

Thanks so much for the reply. However, this does not change the situation:
```
mvn -e validate -Dfile.encoding=UTF-8

[...]

[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoc-to-html) @ com.bedoro.ui ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
Mai 09, 2019 12:45:34 PM org.asciidoctor.jruby.internal.JRubyAsciidoctor convertFile
SCHWERWIEGEND: (ArgumentError) invalid byte sequence in UTF-8

[...]

 Execution asciidoc-to-html of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed: org.jruby.exceptions.ArgumentError: (ArgumentError) invalid byte sequence in UTF-8
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution asciidoc-to-html of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed: org.jruby.exceptions.ArgumentError: (ArgumentError) invalid byte sequence in UTF-8
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.ArgumentError: (ArgumentError) invalid byte sequence in UTF-8
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:379)
        at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:350)
        at org.asciidoctor.maven.AsciidoctorMojo.renderFile(AsciidoctorMojo.java:476)
        at org.asciidoctor.maven.AsciidoctorMojo.execute(AsciidoctorMojo.java:260)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
Caused by: org.jruby.exceptions.ArgumentError: (ArgumentError) invalid byte sequence in UTF-8
        at org.jruby.RubyRegexp.match?(org/jruby/RubyRegexp.java:1153)
        at RUBY.sub_quotes(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/substitutors.rb:190)
        at RUBY.apply_subs(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/substitutors.rb:96)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792)
        at RUBY.apply_subs(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/substitutors.rb:91)
        at RUBY.content(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/block.rb:113)
        at RUBY.convert_paragraph(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/converter/html5.rb:787)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/converter/html5.rb:52)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/abstract_block.rb:75)
        at RUBY.content(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/abstract_block.rb:84)
        at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2577)
        at RUBY.content(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/abstract_block.rb:84)
        at RUBY.content(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/block.rb:111)
        at RUBY.convert_preamble(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/converter/html5.rb:807)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/converter/html5.rb:76)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/abstract_block.rb:75)
        at RUBY.content(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/abstract_block.rb:84)
        at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2577)
        at RUBY.content(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/abstract_block.rb:84)
        at RUBY.content(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/document.rb:1021)
        at RUBY.convert_document(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/converter/html5.rb:227)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/converter/html5.rb:84)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/document.rb:952)
        at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/convert.rb:118)
        at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/convert.rb:183)
        at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1157)
        at RUBY.convert_file(uri:classloader:/gems/asciidoctor-2.0.8/lib/asciidoctor/convert.rb:183)
```

**Comment by mojavelinux** [comment]
That flag should work since that's fundamentally what it does. It might not be making it all the way to AsciidoctorJ. If you can post a sample project on GitHub that we can test, we can debug. Also, I think this should be an AsciidoctorJ issue, not a core issue.
