### ISSUE TITLE
undefined method `empty?' for nil:NilClass when using empty lines inside a Markdown-style blockquote

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#2989]
The source is wrong (it should not contain empty lines inside the blockquote) but it throws an exception:

#### Source
```
> I hold it that a little rebellion now and then is a good thing,

> and as necessary in the political world as storms in the physical.

> -- Thomas Jefferson, Papers of Thomas Jefferson: Volume 11
```

#### Stacktrace
```
asciidoctor test.adoc --trace
/home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:728:in `next_block': asciidoctor: FAILED: /home/guillaume/Bureau/test.adoc: Failed to load AsciiDoc document - undefined method `empty?' for nil:NilClass (NoMethodError)
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:369:in `next_section'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor/parser.rb:98:in `parse'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:570:in `parse'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1367:in `load'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1479:in `convert'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `block in convert_file'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `open'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `convert_file'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `each'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/gems/asciidoctor-1.5.8/bin/asciidoctor:14:in `<top (required)>'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/bin/asciidoctor:22:in `load'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/bin/asciidoctor:22:in `<main>'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/bin/ruby_executable_hooks:15:in `eval'
	from /home/guillaume/.rvm/gems/ruby-2.4.1@asciidoctor-latest/bin/ruby_executable_hooks:15:in `<main>'
```

https://github.com/asciidoctor/asciidoctor/blob/ebb05a60ff7b4d61655d9d4ec33e5e0100f17de8/lib/asciidoctor/parser.rb#L728

**Comment by mojavelinux** [comment]
I wouldn't say the source is wrong. These should be separate quote blocks. So this is just a straight up bug. Nice find!

**Comment by mojavelinux** [comment]
It's even simpler to reproduce:

```
> -- cite
```

Eek!

**Comment by mojavelinux** [comment]
There are many ways we could interpret this. Given that it's not sensible syntax, I think all that really matters is that Asciidoctor not crash.

Here's what I think should be the equivalent:

```
[,cite]
____
____
```

That will result in a quote block with only an attribution (aka cite).

Another possibility is that we don't treat this line as special, but rather as normal quote content. Both are easy to implement.

**Comment by Mogztter** [comment]
Thanks 👍
