### ISSUE TITLE
`block in restore_passthroughs': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3089]
#### Reproduction case

```
echo "pass:m[a] stem:[b]" |  ./bin/asciidoctor - --trace
```
```
/path/to/asciidoctor/lib/asciidoctor/substitutors.rb:319:in `block in restore_passthroughs': undefined method `[]' for nil:NilClass (NoMethodError)
	from /path/to/asciidoctor/lib/asciidoctor/substitutors.rb:316:in `gsub'
	from /path/to/asciidoctor/lib/asciidoctor/substitutors.rb:316:in `restore_passthroughs'
	from /path/to/asciidoctor/lib/asciidoctor/substitutors.rb:112:in `apply_subs'
	from /path/to/asciidoctor/lib/asciidoctor/block.rb:112:in `content'
	from /path/to/asciidoctor/lib/asciidoctor/converter/html5.rb:716:in `paragraph'
	from /path/to/asciidoctor/lib/asciidoctor/converter.rb:376:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /path/to/asciidoctor/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /path/to/asciidoctor/lib/asciidoctor/document.rb:988:in `content'
	from /path/to/asciidoctor/lib/asciidoctor/converter/html5.rb:176:in `document'
	from /path/to/asciidoctor/lib/asciidoctor/converter.rb:376:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/document.rb:919:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor.rb:1463:in `convert'
	from /path/to/asciidoctor/lib/asciidoctor/cli/invoker.rb:106:in `invoke!'
	from ./bin/asciidoctor:15:in `<main>'
```

**Comment by mojavelinux** [comment]
It's even simpler to reproduce.

```
pass:m[.] pass:[.]
```

**Comment by mojavelinux** [comment]
The simplest solution is to add a flag to apply_subs that allows us to keep track of when we're in a nested substitution. Then pass this flag on to restore_passthroughs.

Here's the other solution I considered:

```rb
def restore_passthroughs text, drain = true
  passes = @passthroughs
  passes.tainted? ? (drain = nil) : passes.taint if drain
  text.gsub PassSlotRx do
    pass = passes[$1.to_i] || PASS_UNRESOLVED
    subbed_text = apply_subs(pass[:text], pass[:subs])
    if (type = pass[:type])
      subbed_text = Inline.new(self, :quoted, subbed_text, type: type, attributes: pass[:attributes]).convert
    end
    subbed_text.include?(PASS_START) ? restore_passthroughs(subbed_text, false) : subbed_text
  end
ensure
  passes.clear.untaint if drain
end
```

**Comment by mojavelinux** [comment]
I'm also going to take this opportunity to provide fallback text just in case, for some reason, a matching record cannot be found for the passthrough. This should avoid unexpected crashes in the future.

**Comment by mojavelinux** [comment]
I figured out a slightly better way of doing this that figures out automatically when it's safe to clear the passthroughs.

**Comment by mojavelinux** [comment]
We can't use taint because it's not supported in Opal. Besides, it doesn't communicate very well what's going on. I decided instead to subclass Hash instead and add a lock hint (I say "hint" since it isn't enforced by the Hash implementation).
