### ISSUE TITLE
Graceful error message for wrong attribute definition

### ISSUE THREAD

**Issue by shahryareiv** [asciidoctor/asciidoctor#3096]
If there is a white space after the colon in attribute definition, like this:

```
: WHO: pass:c,a,r,m,q,p[[.acro]#((WHO))#]
```

for a command like this:

```
asciidoctor  -a lang=en  --backend docbook5   --doctype book  -o book.xml book.adoc  --trace
```
It generates, this exception (if trace is on):
```

Traceback (most recent call last):
        33: from /Users/sei/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
        32: from /Users/sei/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
        31: from /Users/sei/.rvm/gems/ruby-2.5.0/bin/asciidoctor:23:in `<main>'
        30: from /Users/sei/.rvm/gems/ruby-2.5.0/bin/asciidoctor:23:in `load'
        29: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/bin/asciidoctor:14:in `<top (required)>'
        28: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
        27: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:112:in `each'
        26: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
        25: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `convert_file'
        24: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `open'
        23: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595:in `block in convert_file'
        22: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
        21: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
        20: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/base.rb:38:in `convert'
        19: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/docbook5.rb:36:in `document'
        18: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1261:in `content'
        17: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `content'
        16: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `map'
        15: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `block in content'
        14: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:75:in `convert'
        13: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/base.rb:38:in `convert'
        12: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/docbook5.rb:371:in `preamble'
        11: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/block.rb:110:in `content'
        10: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `content'
         9: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `map'
         8: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `block in content'
         7: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:75:in `convert'
         6: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/base.rb:38:in `convert'
         5: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/docbook5.rb:364:in `paragraph'
         4: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/block.rb:112:in `content'
         3: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/substitutors.rb:128:in `apply_subs'
         2: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/substitutors.rb:347:in `restore_passthroughs'
         1: from /Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/substitutors.rb:347:in `gsub'
/Users/sei/.rvm/gems/ruby-2.5.0/gems/asciidoctor-1.5.8/lib/asciidoctor/substitutors.rb:350:in `block in restore_passthroughs': undefined method `[]' for nil:NilClass (NoMethodError)
```
IMHO, there should be a more graceful warning/error message as it is very possible to make such mistak (extra white space after colon).

PS: I know one might consider my way of using `pass` in the spirit of Asciidoctor , but anyway I had to implement first-ecounter-expansion of acronyms someway ...

**Comment by mojavelinux** [comment]
I'm happy to report that we just fixed this bug in master. See #3089.

The passthrough placeholders were getting cleared prematurely in certain circumstances. Not only did we fix it, we also added a fallback so that, if for some reason it does happen in another scenario (which we don't anticipate), the processor won't crash.
