### ISSUE TITLE
Regexp MatchData special variables are not properly resolved in Opal

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3214]
As a result the following AsciiDoc contents will be incorrectly parsed:

#### Input

```adoc
ifeval::["{backend}" == "html5"]
Hello HTML5
endif::[]
```

#### Current output

```
start_with?: undefined method `start_with?' for nil
    at constructor.$$method_missing (/home/guillaume/workspace/opensource/nodebook/node_modules/asciidoctor-opal-runtime/src/opal.js:3907:56)
    at constructor.method_missing_stub (/home/guillaume/workspace/opensource/nodebook/node_modules/asciidoctor-opal-runtime/src/opal.js:1310:35)
    at constructor.$$resolve_expr_val (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:14158:68)
    at /home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13648:183
    at constructor.$$preprocess_conditional_directive (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13652:32)
    at constructor.$$process_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13524:37)
    at constructor.$$peek_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:12738:41)
    at Opal.send (/home/guillaume/workspace/opensource/nodebook/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
    at constructor.$$peek_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:13292:29)
    at Function.$$parse_block_metadata_line (/home/guillaume/workspace/opensource/nodebook/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:11211:55)
```

#### Expected output

```html
Hello HTML5
```

#### Input

```adoc
:adjective: strong
pass:normal[*really* {adjective} \]]
```

#### Current output

```html
<p>*really* {adjective} ]</p>
```

#### Expected output

```html
<p><strong>really</strong> strong ]</p>
```

#### Input

```adoc
:value: 4
stem:normal[\\sqrt{{value}} = 2 \]]
```

#### Current output

```html
<p>\$\\sqrt{{value}} = 2 ]\$</p>
```

#### Expected output

```html
<p>\$\\sqrt{4} = 2 ]\$</p>
```

I believe the passthrough syntax with `++` or `+++` is also affected.

**Comment by mojavelinux** [comment]
We need to look for any place where a magic regular expression variable is used after another regular expression has been run. To be safe, we should just ensure that all magic regular expression variables are dereferenced before any other method is called as well (since there's no guarantee what code that method will execute).

**Comment by Mogztter** [comment]
> To be safe, we should just ensure that all magic regular expression variables are dereferenced before any other method is called as well (since there's no guarantee what code that method will execute).

@mojavelinux If you think that performance wise it won't matter then I'm all for it! It really helps to understand the code. When I was working on this issue, I kept going back and forth between the regular expression and the magic regular expression variables because I wasn't sure what part of the match I was looking at.

**Comment by mojavelinux** [comment]
We're still going to use the magic variables, just use them more carefully. The idea is to reference them as soon as possible after the match, and before any functions get called. That's actually a good thing anyway because they will always stay close to the regexp that created them.
