### ISSUE TITLE
rouge syntax highlighter fails when no language is specified

### ISSUE THREAD

**Issue by russau** [asciidoctor/asciidoctor#3223]
To reproduce create a source block with no language specified.

```
$ docker run -it ruby:alpine sh
/ # gem install asciidoctor
Fetching asciidoctor-2.0.4.gem
Successfully installed asciidoctor-2.0.4
1 gem installed
/ # cat << EOF > test.adoc
> :source-highlighter: rouge
> [source]
> --
> puts "I'm a source block!"
> --
> EOF
/ # asciidoctor -o test.html test.adoc
asciidoctor: WARNING: optional gem 'rouge' is not available. Functionality disabled.
undefined method `index' for nil:NilClass
  Use --trace for backtrace
```

Turning on `--trace` gives: `asciidoctor/syntax_highlighter/rouge.rb:39:in `format': undefined method `index' for nil:NilClass (NoMethodError)`

https://github.com/asciidoctor/asciidoctor/blob/0be3fb93423129bf53fffd6248601815f5d99a16/lib/asciidoctor/syntax_highlighter/rouge.rb#L39

**Comment by russau** [comment]
I just noticed the warning about `rouge` not being installed.  Double-check this also gets the `NoMethodError` when `rouge` is installed.

```
/ # gem install rouge
Fetching rouge-3.3.0.gem
Successfully installed rouge-3.3.0
1 gem installed
/ # cat << EOF > test.adoc
> :source-highlighter: rouge
> [source]
> --
> puts "I'm a source block!"
> --
> EOF
/ # asciidoctor -o test.html test.adoc
undefined method `index' for nil:NilClass
  Use --trace for backtrace
```

**Comment by mojavelinux** [comment]
Can you please add the `--trace` flag as suggested by the message?

**Comment by mojavelinux** [comment]
Yep, this is a bug. Here's the beginning of the backtrace:

```
/home/dallen/.rvm/gems/ruby-2.6.1@asciidoctor-testing/gems/asciidoctor-2.0.4/lib/asciidoctor/syntax_highlighter/rouge.rb:39:in `format': undefined method `index' for nil:NilClass (NoMethodError)
	from /home/dallen/.rvm/gems/ruby-2.6.1@asciidoctor-testing/gems/asciidoctor-2.0.4/lib/asciidoctor/converter/html5.rb:661:in `convert_listing'
...
```

**Comment by mojavelinux** [comment]
For reference, Pygments does not fail under the same conditions. It appears we are missing a test.

**Comment by russau** [comment]
Thanks for the quick response!
