### ISSUE TITLE
0.26.13 throws exception "Unable to serialize AsciidocApplicationSettings state"

### ISSUE THREAD

**Issue by twogee** [asciidoctor/asciidoctor#3320]
```
Unable to serialize AsciidocApplicationSettings state

com.intellij.util.xmlb.XmlSerializationException: Can't serialize instance of class org.asciidoc.intellij.settings.AsciiDocApplicationSettings$State
	at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:63)
	at com.intellij.configurationStore.XmlSerializer.serialize$default(xmlSerializer.kt:47)
	at com.intellij.configurationStore.SaveSessionBaseKt.serializeState(SaveSessionBase.kt:46)
	at com.intellij.configurationStore.SaveSessionBase.setState(SaveSessionBase.kt:20)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:283)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:199)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:89)
	at com.intellij.configurationStore.ComponentStoreImpl.doCreateSaveSessionManagerAndCommitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt:155)
	at com.intellij.configurationStore.ComponentStoreImpl$createSaveSessionManagerAndSaveComponents$3.invokeSuspend(ComponentStoreImpl.kt:146)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:236)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at org.asciidoc.intellij.settings.AsciiDocPreviewSettings.equals(AsciiDocPreviewSettings.java:143)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:45)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:57)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:25)
	at com.intellij.util.xmlb.BeanBinding.serializePropertyInto(BeanBinding.java:96)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:80)
	at com.intellij.configurationStore.KotlinAwareBeanBinding.serializeInto(xmlSerializer.kt:235)
	at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:69)
	at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:53)
	... 31 more
```

**Comment by Mogztter** [comment]
Given the stacktrace I believe this is related to the Intellij IDEA plugin ? Could you please describe how to reproduce this error and/or when this error happens ?

This issue should be moved to https://github.com/asciidoctor/asciidoctor-intellij-plugin

**Comment by twogee** [comment]
Sorry about barking the wrong tree. I have no permission to transfer the issue, though.

**Comment by twogee** [comment]
The other issue would be "Asciidoc IntelliJ plugin must refer to the correct Github project for issue reporting" under "IDE fatal errors".

**Comment by Mogztter** [comment]
> Sorry about barking the wrong tree. I have no permission to transfer the issue, though.

No worries, I think only @mojavelinux can do it.

> The other issue would be "Asciidoc IntelliJ plugin must refer to the correct Github project for issue reporting" under "IDE fatal errors".

Indeed, you should open a new issue in https://github.com/asciidoctor/asciidoctor-intellij-plugin

To be fair, since the IntelliJ plugin is using AsciidoctorJ which is using Asciidoctor (Ruby) an issue could potentially track back here. But anyway it's better if the plugin refer to  https://github.com/asciidoctor/asciidoctor-intellij-plugin
