### ISSUE TITLE
Error when using opts for SVG taming 

### ISSUE THREAD

**Issue by mvisaweevil** [asciidoctor/asciidoctor#3352]
The following syntax (using opts) triggs an error.
image::MYLOGO.svg[height=10%,width=10%,align="left",opts=inline]

And could you also proving 1.7.0 version package without jre ?

ERROR => Problem occured while rendering content
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: c1848891-01be-44c6-aca5-0c5eb9e065ac is not completed

	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:159)

	at com.kodedu.engine.AsciidocWebkitConverter.convertAsciidoc(AsciidocWebkitConverter.java:174)

	at com.kodedu.controller.ApplicationController.renderLoop(ApplicationController.java:2367)

	at com.kodedu.controller.ApplicationController.lambda$initializeApp$18(ApplicationController.java:613)

	at com.kodedu.service.ThreadService$1.call(ThreadService.java:48)

	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)

	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)

	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)

	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)

	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Task: c1848891-01be-44c6-aca5-0c5eb9e065ac is not completed

	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)

	at java.util.concurrent.CompletableFuture.get(Unknown Source)

	at com.kodedu.engine.AsciidocWebkitConverter.convert(AsciidocWebkitConverter.java:157)

	... 11 common frames omitted

Caused by: java.lang.RuntimeException: Task: c1848891-01be-44c6-aca5-0c5eb9e065ac is not completed

	at com.kodedu.controller.ApplicationController.lambda$null$171(ApplicationController.java:2312)

	at java.util.Optional.ifPresent(Unknown Source)

	at com.kodedu.controller.ApplicationController.lambda$completeWebWorkerExceptionally$172(ApplicationController.java:2311)

	... 8 common frames omitted

**Comment by abelsromero** [comment]
I assume this is related to AsciidocFX? https://github.com/asciidocfx/AsciidocFX

**Comment by abelsromero** [comment]
Btw, regarding the image configuration, I could not see any error in other asciidoctor converters but noticed that sizing properties define the size in pixels, is not a % scaling. Maybe the issue come from that?

https://asciidoctor.org/docs/user-manual/#summary-2

**Comment by mvisaweevil** [comment]
Yes for sure it is related to Asciidocfx.
For information removing only the opts=xxx part of the image controls makes it working.

**Comment by mojavelinux** [comment]
I'll move this to the appropriate place in that case.

**Comment by mojavelinux** [comment]
Oops, I can't do that since AsciidocFx is not in the Asciidoctor organization. Can you please refile the issue here https://github.com/asciidocfx/AsciidocFX?

**Comment by mvisaweevil** [comment]
Ok sorry for the mistake.

**Comment by mojavelinux** [comment]
No problem. We're happy to help.
