### ISSUE TITLE
asciidoctor error after reinstall with rvm

### ISSUE THREAD

**Issue by janicemhdc** [asciidoctor/asciidoctor#3500]
asciidoctor-pdf stopped working for me and I need to get it working again; you may remember I had installed directly and run into problems (see [asciidoctor-pdf issue #1238](https://github.com/asciidoctor/asciidoctor-pdf/issues/1238)); I had managed to fix them and get asciidoctor-pdf working for a while. I have no idea why it stopped.

Given all of this, I decided to start a fresh install of everything using rvm per instructions on the referenced issue. I installed RVM on my Mac following the instructions here:

https://asciidoctor.org/docs/install-asciidoctor-macos/#rvm-procedure-recommended

and, although it took forever, it seemed to work.

I ran `source /Users/<user>/.rvm/scripts/rvm` per the instructions at the end of the rvm install.

I ran `source $HOME/.bash_profile` per your instructions.

I then installed asciidoctor within rvm using `gem install asciidoctor` and it appeared to work.

However, when I tried it out with `asciidoctor -v` I got the following error:

```:$ gem install asciidoctor
Fetching asciidoctor-2.0.10.gem
Successfully installed asciidoctor-2.0.10
Parsing documentation for asciidoctor-2.0.10
Installing ri documentation for asciidoctor-2.0.10
Done installing documentation for asciidoctor after 2 seconds
1 gem installed
$ asciidoctor -v
Traceback (most recent call last):
	22: from /Users/<user>/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	21: from /Users/<user>/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	20: from /Users/<user>/.rvm/gems/ruby-2.6.3/bin/asciidoctor:23:in `<main>'
	19: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:304:in `activate_bin_path'
	18: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:304:in `synchronize'
	17: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:306:in `block in activate_bin_path'
	16: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems.rb:243:in `finish_resolve'
	15: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:435:in `resolve_current'
	14: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/request_set.rb:423:in `resolve'
	13: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver.rb:188:in `resolve'
	12: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
	11: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
	10: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
	 9: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
	 8: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
	 7: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
	 6: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
	 5: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `sort_dependencies'
	 4: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `with_index'
	 3: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `sort_by'
	 2: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver.rb:277:in `each'
	 1: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver.rb:283:in `block in sort_dependencies'
/usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: user requested 'bundler (= 1.17.2)' (Gem::UnsatisfiableDependencyError)
```

How do I fix this? Do I need asciidoctor working in rvm to install asciidoctor-pdf and get it to work? I have asciidoctor for HTML generation still working external to rvm. It would be a pain and a half to have to go back and forth, but I could do it if needed, especially for the short term.

**Comment by mojavelinux** [comment]
To my knowledge, the latest Asciidoctor and Asciidoctor PDF releases install without issue and the instructions in the docs are correct. If anyone has trouble installing Asciidoctor for whatever reason, you are invited to seek help in the project chat at https://chat.asciidoctor.org.
