### ISSUE TITLE
2.0.11 fails with undefined method `end_with' when using SVG diagram format

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor#3829]
Hi, I noticed that asciidoctor 2.0.11, broke SVG diagrams with the arguments I used.
Reverting to asciidoctor 2.0.10 worked.

```
asciidoctor -r asciidoctor-diagram -a diagram-svg-type=inline -a ditaa-format=svg -a allow-uri-read -a library=asciidoctor-ruby --trace - > /dev/null << EOF
.colored pointer
[ditaa,object-pointer]
----

---->

----
EOF
Traceback (most recent call last):
        17: from /usr/local/Cellar/asciidoctor/2.0.11/libexec/bin/asciidoctor:23:in `<main>'
        16: from /usr/local/Cellar/asciidoctor/2.0.11/libexec/bin/asciidoctor:23:in `load'
        15: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/bin/asciidoctor:15:in `<top (required)>'
        14: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/cli/invoker.rb:110:in `invoke!'
        13: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/convert.rb:119:in `convert'
        12: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/document.rb:936:in `convert'
        11: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/converter/html5.rb:84:in `convert'
        10: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/converter/html5.rb:226:in `convert_document'
         9: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/document.rb:1005:in `content'
         8: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/abstract_block.rb:84:in `content'
         7: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/abstract_block.rb:84:in `map'
         6: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/abstract_block.rb:84:in `block in content'
         5: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/abstract_block.rb:75:in `convert'
         4: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/converter/html5.rb:65:in `convert'
         3: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/converter/html5.rb:630:in `convert_image'
         2: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/converter/html5.rb:1270:in `read_svg_contents'
         1: from /Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/converter/html5.rb:1270:in `each'
/Users/bric3/.gem/ruby/2.6.0/gems/asciidoctor-2.0.11/lib/asciidoctor/converter/html5.rb:1276:in `block in read_svg_contents': undefined method `end_with?' for 90:Integer (NoMethodError)

```

--------

```
gem query --local

*** LOCAL GEMS ***

asciidoctor (2.0.11, 2.0.10)
asciidoctor-diagram (2.0.5, 2.0.4, 2.0.3, 2.0.2)
asciidoctor-html5s (0.5.0, 0.4.1)
bigdecimal (2.0.0, default: 1.4.1)
bundler (2.1.4, default: 1.17.2)
CFPropertyList (3.0.2, 2.3.6)
cmath (default: 1.0.0)
csv (3.1.7, 3.1.6, 3.1.5, 3.1.3, 3.1.2, default: 3.0.9)
date (3.0.1, 3.0.0, default: 2.0.0)
dbm (1.1.0, default: 1.0.0)
did_you_mean (1.4.0, 1.3.0)
e2mmap (default: 0.1.0)
etc (1.1.0, default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (1.4.1, default: 1.1.0)
forwardable (1.3.1, default: 1.2.0)
hpricot (0.8.6)
io-console (0.5.6, 0.5.5, 0.5.4, default: 0.4.7)
ipaddr (default: 1.2.2)
irb (1.2.7, 1.2.6, 1.2.4, 1.2.3, 1.2.1, default: 1.0.0)
json (2.3.1, 2.3.0, default: 2.1.0)
libxml-ruby (3.2.1, 3.2.0, 3.1.0)
logger (1.4.2, default: 1.3.0)
matrix (0.3.0, default: 0.1.0)
mini_portile2 (2.5.0, 2.4.0)
minitest (5.14.2, 5.14.1, 5.14.0, 5.11.3)
mustache (1.1.1)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
nokogiri (1.10.10, 1.10.9, 1.10.8, 1.10.7, 1.10.1)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.2.0, 1.1.7, 1.1.6, 1.1.5, 1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (13.0.1, 12.3.2)
rdiscount (2.2.0.1)
rdoc (6.2.1, default: 6.1.0)
reline (0.1.5, 0.1.4, 0.1.3, 0.1.2)
rexml (3.2.4, 3.2.3, default: 3.1.9)
ronn (0.7.3)
rss (0.2.9, 0.2.8, default: 0.2.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (0.8.0, default: 0.7)
sqlite3 (1.4.2, 1.3.13)
stringio (0.1.3, 0.1.0, default: 0.0.2)
strscan (1.0.3, default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.3.5, 3.2.9)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (1.6.0, default: 1.4.2)
xmlrpc (0.3.0)
zlib (1.1.0, default: 1.0.0)
```

**Comment by mojavelinux** [comment]
It looks like Asciidoctor Diagram is setting either the width or height attribute to an integer. The converter expects these values to be strings.

**Comment by mojavelinux** [comment]
You are correct that 2.0.10 didn't care that the value was a number. It seems reasonable to check the type in this case since this is coming from another library.

**Comment by mojavelinux** [comment]
The reason this situation came up is because the converter is trying to append the "px" unit identifier to the value if the value is not a percentage (i.e., does not end with "%"). However, this is unnecessary since the default unit identifier for SVG in HTML is "px".

> If the width or height presentation attributes on the outermost svg element are in user units (i.e., no unit identifier has been provided), then the value is assumed to be equivalent to the same number of "px" units (from https://www.w3.org/TR/SVG/coords.html#ViewportSpace)

So it's best to just to pass through the values as is.
