### ISSUE TITLE
counter should ignore values that are not an integer or a single character

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor#3940]
Here are a few edge cases where the behavior is not clearly defined:

#### String starting with a letter

Asciidoctor takes the first character (the letter `h`) and increment it to `i`:

```console
$ echo '{counter2:salutation:hello} {salutation} {counter:salutation}' | asciidoctor -s -
<div class="paragraph">
<p> hello i</p>
</div>
```

#### String starting with a number

Asciidoctor takes the first character (the number `1`) and increment it to `2`:

```console
$ echo '{counter2:math:1x} {math} {counter:math}' | asciidoctor -s - 
<div class="paragraph">
<p> 1x 2</p>
</div>
```

#### Emoji

Asciidoctor takes the value of the emoji character 😋 and increment it to 1 but the value `128524` is out of the char range:

```console
$ echo '{counter2:emoji:😋} {emoji} {counter:emoji}' | asciidoctor -s --trace - 
/path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/helpers.rb:280:in `chr': 128524 out of char range (RangeError)
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/helpers.rb:280:in `nextval'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:566:in `counter'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:232:in `block in sub_attributes'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:214:in `gsub'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:214:in `sub_attributes'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:98:in `block in apply_subs'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:91:in `each'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:91:in `apply_subs'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/block.rb:113:in `content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:791:in `convert_paragraph'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:52:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:324:in `convert_embedded'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:62:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:110:in `invoke!'
	from /path/to/ruby/gems/asciidoctor-2.0.12/bin/asciidoctor:15:in `<top (required)>'
	from /path/to/ruby/bin/asciidoctor:23:in `load'
	from /path/to/ruby/bin/asciidoctor:23:in `<main>'
	from /path/to/ruby/bin/ruby_executable_hooks:15:in `eval'
	from /path/to/ruby/bin/ruby_executable_hooks:15:in `<main>'
```

#### Accent `é`

Not sure what is happening in this case:

```console
$ echo '{counter2:accent:é} {accent} {counter:accent}' | asciidoctor -s --trace -
/path/to/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:214:in `gsub': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:214:in `sub_attributes'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:98:in `block in apply_subs'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:91:in `each'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/substitutors.rb:91:in `apply_subs'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/block.rb:113:in `content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:791:in `convert_paragraph'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:52:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:324:in `convert_embedded'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/converter/html5.rb:62:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
	from /path/to/ruby/gems/asciidoctor-2.0.12/lib/asciidoctor/cli/invoker.rb:110:in `invoke!'
	from /path/to/ruby/gems/asciidoctor-2.0.12/bin/asciidoctor:15:in `<top (required)>'
	from /path/to/ruby/bin/asciidoctor:23:in `load'
	from /path/to/ruby/bin/asciidoctor:23:in `<main>'
	from /path/to/ruby/bin/ruby_executable_hooks:15:in `eval'
	from /path/to/ruby/bin/ruby_executable_hooks:15:in `<main>'
```

I think Asciidoctor should ignore unexpected values to prevent potential abuse or misusage.

**Comment by mojavelinux** [comment]
I think the logic that handles this in Asciidoctor is a bit outdated. There's already a method on String named [succ](https://ruby-doc.org/core-2.6.3/String.html#method-i-succ) that would give us the next logical string in the sequence. This will handle all the single character strings fine and will gracefully handle multi-character strings, even if the result is a bit odd.
