### ISSUE TITLE
can't find gem asciidoctor

### ISSUE THREAD

**Issue by marmalodak** [asciidoctor/asciidoctor#3986]
I don't know enough about the ruby ecosystem to know what this means.
```
Ignoring executable-hooks-1.6.1 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.1
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Traceback (most recent call last):
        2: from /usr/bin/asciidoctor:23:in `<main>'
        1: from /usr/share/rubygems/rubygems.rb:296:in `activate_bin_path'
/usr/share/rubygems/rubygems.rb:277:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
```
Fedora 33.

**Comment by mojavelinux** [comment]
Please ask support questions in the community chat at https://asciidoctor.zulipchat.com. Thanks!
