### ISSUE TITLE
'undefined method rindex' when calling load and setting to_file with boolean

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor#4055]
v2.0.15

Passing a boolean value to `to_file` option while calling `load` method causes the error:

```
Traceback (most recent call last):
        4: from load.rb:3:in `<main>'
        3: from /home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/load.rb:83:in `load'
        2: from /home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/load.rb:83:in `new'
        1: from /home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:315:in `initialize'
/home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/helpers.rb:227:in `extname': undefined method `rindex' for true:TrueClass (NoMethodError)
        4: from load.rb:3:in `<main>'
        3: from /home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/load.rb:83:in `load'
        2: from /home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/load.rb:83:in `new'
        1: from /home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/document.rb:315:in `initialize'
/home//.rvm/gems/ruby-2.7.0/gems/asciidoctor-2.0.15/lib/asciidoctor/helpers.rb:227:in `extname': asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `rindex' for true:TrueClass (NoMethodError)
```

This can be reproduced with script:

```ruby
require 'asciidoctor'

Asciidoctor.load("= p1039", to_file: true)
```

**Comment by mojavelinux** [comment]
Note that this is related to #2435, but should be fixed separately.
