### ISSUE TITLE
"undefined method `absolute_path?' "

### ISSUE THREAD

**Issue by jnk0le** [asciidoctor/asciidoctor#4433]
I have previously working workflow that suddenly started throwing errors in asciidoctor step.

https://github.com/jnk0le/XTightlyCoupledIO/commit/687f4fe64f4c546a549fc1c9918a3c3983e2f7d7

```
Run PATH=${PATH}:${BUNDLE_BIN}:$(npm bin) \
  PATH=${PATH}:${BUNDLE_BIN}:$(npm bin) \
  make ${PDF_RESULT}
  shell: /usr/bin/bash -e {0}
  env:
    APT_PACKAGES_FILE: /home/runner/work/XTightlyCoupledIO/XTightlyCoupledIO/dependencies/apt_packages.txt
    BUNDLE_GEMFILE: /home/runner/work/XTightlyCoupledIO/XTightlyCoupledIO/dependencies/Gemfile
    BUNDLE_BIN: /home/runner/work/XTightlyCoupledIO/XTightlyCoupledIO/bin
    NPM_PACKAGE_FOLDER: /home/runner/work/XTightlyCoupledIO/XTightlyCoupledIO/dependencies
    PDF_RESULT: XTightlyCoupledIO.pdf
asciidoctor-pdf \
-a compress \
--require=asciidoctor-diagram \
--out-file=XTightlyCoupledIO.pdf \
xtightlycoupledio.adoc
undefined method `absolute_path?' for File:Class
Did you mean?  absolute_path
  Use --trace to show backtrace
make: *** [Makefile:10: XTightlyCoupledIO.pdf] Error 1
Error: Process completed with exit code 2.
```

and with trace (different repo)

```
Run PATH=${PATH}:${BUNDLE_BIN}:$(npm bin) \
  PATH=${PATH}:${BUNDLE_BIN}:$(npm bin) \
  make ${PDF_RESULT}
  shell: /usr/bin/bash -e {0}
  env:
    APT_PACKAGES_FILE: /home/runner/work/riscv-total-embedded/riscv-total-embedded/dependencies/apt_packages.txt
    BUNDLE_GEMFILE: /home/runner/work/riscv-total-embedded/riscv-total-embedded/dependencies/Gemfile
    BUNDLE_BIN: /home/runner/work/riscv-total-embedded/riscv-total-embedded/bin
    NPM_PACKAGE_FOLDER: /home/runner/work/riscv-total-embedded/riscv-total-embedded/dependencies
    PDF_RESULT: riscv-total-embedded.pdf
asciidoctor-pdf \
-a compress \
--require=asciidoctor-diagram \
--out-file=riscv-total-embedded.pdf \
--trace \
riscv-total-embedded.adoc
/home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:4290:in `resolve_image_path': undefined method `absolute_path?' for File:Class (NoMethodError)
Did you mean?  absolute_path
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:1715:in `convert_image'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:152:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:2386:in `traverse'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:682:in `convert_section'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:152:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:2386:in `traverse'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:682:in `convert_section'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:152:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:2386:in `traverse'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:682:in `convert_section'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:152:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:1012:in `content'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:2386:in `traverse'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:292:in `block in convert_document'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:616:in `indent_section'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:200:in `convert_document'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/lib/asciidoctor/pdf/converter.rb:152:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:956:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:118:in `convert'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:190:in `block in convert_file'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:190:in `open'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:190:in `convert_file'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/cli/invoker.rb:129:in `block in invoke!'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/cli/invoker.rb:112:in `each'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-2.0.18/lib/asciidoctor/cli/invoker.rb:112:in `invoke!'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/vendor/bundle/ruby/2.6.0/gems/asciidoctor-pdf-2.3.6/bin/asciidoctor-pdf:46:in `<top (required)>'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/bin/asciidoctor-pdf:27:in `load'
	from /home/runner/work/riscv-total-embedded/riscv-total-embedded/bin/asciidoctor-pdf:27:in `<main>'
make: *** [Makefile:10: riscv-total-embedded.pdf] Error 1
Error: Process completed with exit code 2.
```

looks like classic "managed language" typo in code

**Comment by jnk0le** [comment]
On further testing it seems related to wavedrom images 
```
[wavedrom, , svg]
```
